Change type conversion from float/dfloat to real
dftbplus/skprogs pull request #12
Opened 2021-12-05 05:28 UTC by tsihyoung

Change type conversions in `slateratom/lib` from `float` or `dfloat` to `real(,dp)`.

2022-01-07 16:26 UTC, aradi requested changes
Thanks for the PR! I agree with all the changes `float` and `dfloat` to `real(dp)`. But please remove everything else (especially the libxc upgrade), that belongs into a separate PR.

2022-01-07 16:26 UTC, aradi commented on README.rst
> +* LibXC library with f90 interface (tested with version 5.1.6, version 4.x does
Note, at this stage the code still uses the old interface, this belongs to the other PR.

2022-01-07 16:26 UTC, aradi commented on README.rst
> +    FC=gfortran cmake -DCMAKE_INSTALL_PREFIX=$HOME/opt/skprogs -DCMAKE_Fortran_FLAGS=-fopenmp -B _build .
Please remove the `-fopenmp` flag. OpenMP support should be added via OpenMP-detection in CMake and linking against the `OpenMP::OpenMP_Fortran` target.

2022-01-07 16:26 UTC, aradi commented on README.rst
> +    FC=ifort cmake -DCMAKE_INSTALL_PREFIX=$HOME/opt/skprogs -DCMAKE_Fortran_FLAGS=-qopenmp -B _build .
I think, this 2nd example is superfluous. (SkProgs should work with any standard conforming compiler, gfortran is just an example.)

2022-01-07 16:26 UTC, aradi commented on README.rst
> +    PKG_CONFIG_PATH=FOLDER_WITH_LIBXC_PC_FILES FC=ifort cmake [...]
Again, this is superfluous. Also, the `CMAKE_PREFIX_PATH` example will only work if we upgrade to recent libxc, so that belongs into the other PR.

2022-01-07 16:26 UTC, aradi commented on slateratom/lib/dft.f90
> +    type(xc_f90_func_info_t) :: xcinfo
That would only work with libxc 5.x

2022-01-07 16:26 UTC, aradi commented on slateratom/lib/dft.f90
> +      xcinfo = xc_f90_func_get_info(xcfunc_x)
Belong into a separate PR which upgrades libxc

2022-01-08 03:31 UTC, tsihyoung commented
> `at` to `real(dp)`. But please remove everything else (especially the libxc upgrade), that belongs into a separate PR.

Thanks for reviewing this PR. I have removed the libxc interface changes and modified the README file.

2022-01-27 14:20 UTC, merged